obj = input("Pick an object (0-9): ")

if obj == "0":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 01 = 1)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 2")
            elif enemy == "5": print("Result: 5")
            elif enemy == "7": print("Result: 7")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 0.5")
            elif enemy == "5": print("Result: 0.2")
            elif enemy == "7": print("Result: 0.14")
    elif tool == "8": # Spyglass (Base 08 = 8)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 16")
            elif enemy == "5": print("Result: 40")
            elif enemy == "7": print("Result: 56")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 4.0")
            elif enemy == "5": print("Result: 1.6")
            elif enemy == "7": print("Result: 1.14")
    elif tool == "9": # Axe (Base 09 = 9)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 18")
            elif enemy == "5": print("Result: 45")
            elif enemy == "7": print("Result: 63")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 4.5")
            elif enemy == "5": print("Result: 1.8")
            elif enemy == "7": print("Result: 1.29")

if obj == "1":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 11)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 22")
            elif enemy == "5": print("Result: 55")
            elif enemy == "7": print("Result: 77")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 5.5")
            elif enemy == "5": print("Result: 2.2")
            elif enemy == "7": print("Result: 1.57")
    elif tool == "8": # Spyglass (Base 18)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 36")
            elif enemy == "5": print("Result: 90")
            elif enemy == "7": print("Result: 126")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 9.0")
            elif enemy == "5": print("Result: 3.6")
            elif enemy == "7": print("Result: 2.57")
    elif tool == "9": # Axe (Base 19)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 38")
            elif enemy == "5": print("Result: 95")
            elif enemy == "7": print("Result: 133")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 9.5")
            elif enemy == "5": print("Result: 3.8")
            elif enemy == "7": print("Result: 2.71")

if obj == "2":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 21)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 42")
            elif enemy == "5": print("Result: 105")
            elif enemy == "7": print("Result: 147")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 10.5")
            elif enemy == "5": print("Result: 4.2")
            elif enemy == "7": print("Result: 3.0")
    elif tool == "8": # Spyglass (Base 28)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 56")
            elif enemy == "5": print("Result: 140")
            elif enemy == "7": print("Result: 196")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 14.0")
            elif enemy == "5": print("Result: 5.6")
            elif enemy == "7": print("Result: 4.0")
    elif tool == "9": # Axe (Base 29)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 58")
            elif enemy == "5": print("Result: 145")
            elif enemy == "7": print("Result: 203")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 14.5")
            elif enemy == "5": print("Result: 5.8")
            elif enemy == "7": print("Result: 4.14")

if obj == "3":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 31)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 62")
            elif enemy == "5": print("Result: 155")
            elif enemy == "7": print("Result: 217")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 15.5")
            elif enemy == "5": print("Result: 6.2")
            elif enemy == "7": print("Result: 4.43")
    elif tool == "8": # Spyglass (Base 38)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 76")
            elif enemy == "5": print("Result: 190")
            elif enemy == "7": print("Result: 266")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 19.0")
            elif enemy == "5": print("Result: 7.6")
            elif enemy == "7": print("Result: 5.43")
    elif tool == "9": # Axe (Base 39)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 78")
            elif enemy == "5": print("Result: 195")
            elif enemy == "7": print("Result: 273")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 19.5")
            elif enemy == "5": print("Result: 7.8")
            elif enemy == "7": print("Result: 5.57")

if obj == "4":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 41)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 82")
            elif enemy == "5": print("Result: 205")
            elif enemy == "7": print("Result: 287")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 20.5")
            elif enemy == "5": print("Result: 8.2")
            elif enemy == "7": print("Result: 5.86")
    elif tool == "8": # Spyglass (Base 48)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 96")
            elif enemy == "5": print("Result: 240")
            elif enemy == "7": print("Result: 336")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 24.0")
            elif enemy == "5": print("Result: 9.6")
            elif enemy == "7": print("Result: 6.86")
    elif tool == "9": # Axe (Base 49)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 98")
            elif enemy == "5": print("Result: 245")
            elif enemy == "7": print("Result: 343")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 24.5")
            elif enemy == "5": print("Result: 9.8")
            elif enemy == "7": print("Result: 7.0")

if obj == "5":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 51)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 102")
            elif enemy == "5": print("Result: 255")
            elif enemy == "7": print("Result: 357")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 25.5")
            elif enemy == "5": print("Result: 10.2")
            elif enemy == "7": print("Result: 7.29")
    elif tool == "8": # Spyglass (Base 58)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 116")
            elif enemy == "5": print("Result: 290")
            elif enemy == "7": print("Result: 406")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 29.0")
            elif enemy == "5": print("Result: 11.6")
            elif enemy == "7": print("Result: 8.29")
    elif tool == "9": # Axe (Base 59)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 118")
            elif enemy == "5": print("Result: 295")
            elif enemy == "7": print("Result: 413")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 29.5")
            elif enemy == "5": print("Result: 11.8")
            elif enemy == "7": print("Result: 8.43")

if obj == "6":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 61)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 122")
            elif enemy == "5": print("Result: 305")
            elif enemy == "7": print("Result: 427")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 30.5")
            elif enemy == "5": print("Result: 12.2")
            elif enemy == "7": print("Result: 8.71")
    elif tool == "8": # Spyglass (Base 68)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 136")
            elif enemy == "5": print("Result: 340")
            elif enemy == "7": print("Result: 476")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 34.0")
            elif enemy == "5": print("Result: 13.6")
            elif enemy == "7": print("Result: 9.71")
    elif tool == "9": # Axe (Base 69)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 138")
            elif enemy == "5": print("Result: 345")
            elif enemy == "7": print("Result: 483")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 34.5")
            elif enemy == "5": print("Result: 13.8")
            elif enemy == "7": print("Result: 9.86")

if obj == "7":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 71)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 142")
            elif enemy == "5": print("Result: 355")
            elif enemy == "7": print("Result: 497")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 35.5")
            elif enemy == "5": print("Result: 14.2")
            elif enemy == "7": print("Result: 10.14")
    elif tool == "8": # Spyglass (Base 78)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 156")
            elif enemy == "5": print("Result: 390")
            elif enemy == "7": print("Result: 546")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 39.0")
            elif enemy == "5": print("Result: 15.6")
            elif enemy == "7": print("Result: 11.14")
    elif tool == "9": # Axe (Base 79)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 158")
            elif enemy == "5": print("Result: 395")
            elif enemy == "7": print("Result: 553")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 39.5")
            elif enemy == "5": print("Result: 15.8")
            elif enemy == "7": print("Result: 11.29")

if obj == "8":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 81)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 162")
            elif enemy == "5": print("Result: 405")
            elif enemy == "7": print("Result: 567")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 40.5")
            elif enemy == "5": print("Result: 16.2")
            elif enemy == "7": print("Result: 11.57")
    elif tool == "8": # Spyglass (Base 88)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 176")
            elif enemy == "5": print("Result: 440")
            elif enemy == "7": print("Result: 616")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 44.0")
            elif enemy == "5": print("Result: 17.6")
            elif enemy == "7": print("Result: 12.57")
    elif tool == "9": # Axe (Base 89)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 178")
            elif enemy == "5": print("Result: 445")
            elif enemy == "7": print("Result: 623")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 44.5")
            elif enemy == "5": print("Result: 17.8")
            elif enemy == "7": print("Result: 12.71")

if obj == "9":
    print("Sword(1), Spyglass(8), Axe(9)")
    tool = input("Pick a tool: ")
    if tool == "1": # Sword (Base 91)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 182")
            elif enemy == "5": print("Result: 455")
            elif enemy == "7": print("Result: 637")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 45.5")
            elif enemy == "5": print("Result: 18.2")
            elif enemy == "7": print("Result: 13.0")
    elif tool == "8": # Spyglass (Base 98)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 196")
            elif enemy == "5": print("Result: 490")
            elif enemy == "7": print("Result: 686")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 49.0")
            elif enemy == "5": print("Result: 19.6")
            elif enemy == "7": print("Result: 14.0")
    elif tool == "9": # Axe (Base 99)
        print("Treasure(x), 1 v 1(/)")
        action = input("Pick an action: ")
        if action == "x":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 198")
            elif enemy == "5": print("Result: 495")
            elif enemy == "7": print("Result: 693")
        elif action == "/":
            print("Grandma(2), Snake(5), Pirate(7)")
            enemy = input("Pick who to fight: ")
            if enemy == "2": print("Result: 49.5")
            elif enemy == "5": print("Result: 19.8")
            elif enemy == "7": print("Result: 14.14")